{
    "name": "Remuneraciones Chile",
    "version": "1.0",
    "depends": ["base", "mail"],
    "author": "Auto Generated",
    "category": "Human Resources",
    "description": "Gestión de remuneraciones para Chile",
    "data": [
        "security/ir.model.access.csv",
        "views/afp_views.xml",
        "views/isapre_views.xml",
        "views/tabla_impuesto_views.xml",
        "views/parametros_mes_views.xml",
        "views/haber_views.xml",
        "views/descuento_views.xml",
        "views/empresa_views.xml",
        "views/unidad_views.xml",
        "views/cargo_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": True,
}
